version: 2

references:
  circleci_docker_primary: &circleci_docker_primary trussworks/circleci-docker-primary:abca33ce0067fe58a4e33139ae470b65f1cab1f9

jobs:
  terratest:
    docker:
      - image: *circleci_docker_primary
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-sources-v1-{{ checksum "go.sum" }}
      - run:
          name: Assume role, run pre-commit and run terratest
          command: |
            temp_role=$(aws sts assume-role \
                    --role-arn arn:aws:iam::313564602749:role/circleci \
                    --role-session-name circleci)
            export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
            export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
            export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
            go test -v -timeout 90m -run 'TestTerraformAwsLogs(Nlb|Elb|Alb|S3)' ./test/
      - save_cache:
          key: go-mod-sources-v1-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"

workflows:
  version: 2
  validate:
    jobs:
      - terratest
